import { PrismaClient } from "@prisma/client";

export async function seedDivisionServicio(prisma: PrismaClient) {
  console.log("🏭 Creando divisiones, unidades y transporte...");

  const divisiones = [
    { codigo: "SOLIDO", descripcion: "Transporte de Carga Sólida" },
    { codigo: "LIQUIDO", descripcion: "Transporte de Carga Líquida" },
    { codigo: "GRANEL", descripcion: "Transporte de Carga a Granel" },
    { codigo: "TODOS", descripcion: "TRACTOR-Carga definida en el trailer" },
  ];

  const unidades = [
    { codigo: "bbl", descripcion: "Barril", division: "LIQUIDO" },
    { codigo: "bag", descripcion: "Bolsa", division: "SOLIDO" },
    { codigo: "box", descripcion: "Caja", division: "SOLIDO" },
    { codigo: "cnt", descripcion: "Ciento", division: "SOLIDO" },
    { codigo: "container", descripcion: "Contenedor", division: "TODOS" },
    {
      codigo: "TEU",
      descripcion: "Contenedor 20 pies (TEU)",
      division: "TODOS",
    },
    {
      codigo: "FEU",
      descripcion: "Contenedor 40 pies (FEU)",
      division: "TODOS",
    },
    {
      codigo: "High Cube",
      descripcion: "Contenedor High Cube (40 pies alto)",
      division: "TODOS",
    },
    { codigo: "qt", descripcion: "Cuarto de galón", division: "LIQUIDO" },
    { codigo: "daL", descripcion: "Decalitro", division: "LIQUIDO" },
    { codigo: "doz", descripcion: "Docena", division: "SOLIDO" },
    { codigo: "bndl", descripcion: "Fardo", division: "SOLIDO" },
    { codigo: "gal", descripcion: "Galón (US y UK)", division: "LIQUIDO" },
    { codigo: "g", descripcion: "Gramo", division: "SOLIDO" },
    { codigo: "hL", descripcion: "Hectolitro", division: "LIQUIDO" },
    { codigo: "kg", descripcion: "Kilogramo", division: "SOLIDO" },
    { codigo: "lb", descripcion: "Libra", division: "SOLIDO" },
    { codigo: "l", descripcion: "Litro", division: "LIQUIDO" },
    {
      codigo: "l(gc)",
      descripcion: "Litro (gas comprimido)",
      division: "LIQUIDO",
    },
    { codigo: "lote", descripcion: "Lote", division: "SOLIDO" },
    { codigo: "m³", descripcion: "Metro cúbico", division: "GRANEL" },
    { codigo: "mt³", descripcion: "Metro cúbico GAS", division: "LIQUIDO" },
    {
      codigo: "Nm³",
      descripcion: "Metro cúbico normalizado",
      division: "GRANEL",
    },
    { codigo: "oz", descripcion: "Onza", division: "SOLIDO" },
    { codigo: "pllt", descripcion: "Palé", division: "SOLIDO" },
    {
      codigo: "palé estándar",
      descripcion: "Palé estándar (800 mm x 1200 mm)",
      division: "SOLIDO",
    },
    {
      codigo: "palé industrial",
      descripcion: "Palé industrial (1000 mm x 1200 mm)",
      division: "SOLIDO",
    },
    { codigo: "pck", descripcion: "Paquete", division: "SOLIDO" },
    { codigo: "scf", descripcion: "Pie cúbico estándar", division: "GRANEL" },
    { codigo: "pcs", descripcion: "Piezas", division: "SOLIDO" },
    { codigo: "qq", descripcion: "Quintal métrico", division: "SOLIDO" },
    { codigo: "roll", descripcion: "Rollo", division: "SOLIDO" },
    { codigo: "sck", descripcion: "Saco", division: "SOLIDO" },
    { codigo: "t", descripcion: "Tonelada métrica", division: "SOLIDO" },
  ];

  const clases = [
    { codigo: "CHASIS", descripcion: "Clase de Chasis" },
    { codigo: "TRAILER", descripcion: "Clase de Trailer" },
    { codigo: "TRACTOR", descripcion: "Clase de Tractor" },
    { codigo: "TRACTOR-BALANCIN", descripcion: "Clase de Tractor-Balancin" },
  ];

  const clasificaciones = [
    {
      denominacion: "Chasis con caja de 5,20 m",
      clase: "CHASIS",
      division: "SOLIDO",
      largo: 13.2,
      ancho: 2.6,
      alto: 4.3,
      pesoKg: 16500,
      europaleta: 8,
      arlog: 8,
      americano: 8,
    },
    {
      denominacion: "Chasis con caja de 5,50 m",
      clase: "CHASIS",
      division: "SOLIDO",
      largo: 13.2,
      ancho: 2.6,
      alto: 4.3,
      pesoKg: 16500,
      europaleta: 10,
      arlog: 10,
      americano: 10,
    },
    {
      denominacion: "Chasis con caja de 6,50 m",
      clase: "CHASIS",
      division: "SOLIDO",
      largo: 13.2,
      ancho: 2.6,
      alto: 4.3,
      pesoKg: 16500,
      europaleta: 12,
      arlog: 12,
      americano: 12,
    },
    {
      denominacion: "Chasis con caja de 7,50 m",
      clase: "CHASIS",
      division: "SOLIDO",
      largo: 13.2,
      ancho: 2.6,
      alto: 4.3,
      pesoKg: 16500,
      europaleta: 14,
      arlog: 14,
      americano: 14,
    },
    {
      denominacion: "Chasis dos ejes 7,50 m",
      clase: "CHASIS",
      division: "SOLIDO",
      largo: 13.2,
      ancho: 2.6,
      alto: 4.3,
      pesoKg: 24000,
      europaleta: 14,
      arlog: 14,
      americano: 14,
    },
    {
      denominacion: "Chasis dos ejes 8,50 m",
      clase: "CHASIS",
      division: "SOLIDO",
      largo: 13.2,
      ancho: 2.6,
      alto: 4.3,
      pesoKg: 24000,
      europaleta: 16,
      arlog: 16,
      americano: 16,
    },
    {
      denominacion: "Chasis tres ejes con caja de 8,5 m",
      clase: "CHASIS",
      division: "SOLIDO",
      largo: 13.2,
      ancho: 2.6,
      alto: 4.3,
      pesoKg: 31500,
      europaleta: 16,
      arlog: 16,
      americano: 16,
    },
    {
      denominacion: "Chasis Balancin dos ejes rodados dobles con c/ 7,50 m",
      clase: "CHASIS",
      division: "SOLIDO",
      largo: 13.2,
      ancho: 2.6,
      alto: 4.3,
      pesoKg: 28000,
      europaleta: 14,
      arlog: 14,
      americano: 14,
    },
    {
      denominacion: "Chasis Balancin dos ejes rodados dobles con c/ 8,50 m",
      clase: "CHASIS",
      division: "SOLIDO",
      largo: 13.2,
      ancho: 2.6,
      alto: 4.3,
      pesoKg: 28000,
      europaleta: 16,
      arlog: 16,
      americano: 16,
    },
    {
      denominacion: "Chasis Balancin tres ejes rodados dobles c/ 7,50 m",
      clase: "CHASIS",
      division: "SOLIDO",
      largo: 13.2,
      ancho: 2.6,
      alto: 4.3,
      pesoKg: 35500,
      europaleta: 14,
      arlog: 14,
      americano: 14,
    },
    {
      denominacion: "Chasis Balancin tres ejes rodados dobles c/ 8,50 m",
      clase: "CHASIS",
      division: "SOLIDO",
      largo: 13.2,
      ancho: 2.6,
      alto: 4.3,
      pesoKg: 35500,
      europaleta: 16,
      arlog: 16,
      americano: 16,
    },
    {
      denominacion: "Chasis dos ejes rodados individuales y dobles c/ 7,50 m",
      clase: "CHASIS",
      division: "SOLIDO",
      largo: 13.2,
      ancho: 2.6,
      alto: 4.3,
      pesoKg: 30000,
      europaleta: 14,
      arlog: 14,
      americano: 14,
    },
    {
      denominacion: "Chasis dos ejes rodados individuales y dobles c/ 8,50 m",
      clase: "CHASIS",
      division: "SOLIDO",
      largo: 13.2,
      ancho: 2.6,
      alto: 4.3,
      pesoKg: 30000,
      europaleta: 16,
      arlog: 16,
      americano: 16,
    },
    {
      denominacion: "Chasis tres ejes rodados doble e individuales c/ 7,50 m",
      clase: "CHASIS",
      division: "SOLIDO",
      largo: 13.2,
      ancho: 2.6,
      alto: 4.3,
      pesoKg: 37500,
      europaleta: 14,
      arlog: 14,
      americano: 14,
    },
    {
      denominacion: "Chasis tres ejes rodados doble e individuales c/ 8,50 m",
      clase: "CHASIS",
      division: "SOLIDO",
      largo: 13.2,
      ancho: 2.6,
      alto: 4.3,
      pesoKg: 37500,
      europaleta: 16,
      arlog: 16,
      americano: 16,
    },
    {
      denominacion: "Semiremolque un eje 10,5 m",
      clase: "TRAILER",
      division: "SOLIDO",
      largo: 18.6,
      ancho: 2.6,
      alto: 4.3,
      pesoKg: 27000,
      europaleta: 20,
      arlog: 20,
      americano: 20,
    },
    {
      denominacion: "Semiremolque un eje 13,5 m",
      clase: "TRAILER",
      division: "SOLIDO",
      largo: 18.6,
      ancho: 2.6,
      alto: 4.3,
      pesoKg: 27000,
      europaleta: 26,
      arlog: 26,
      americano: 26,
    },
    {
      denominacion: "Semiremolque dos ejes 13,5 m",
      clase: "TRAILER",
      division: "SOLIDO",
      largo: 18.6,
      ancho: 2.6,
      alto: 4.3,
      pesoKg: 34500,
      europaleta: 26,
      arlog: 26,
      americano: 26,
    },
    {
      denominacion: "Semiremolque dos ejes 14,5 m",
      clase: "TRAILER",
      division: "SOLIDO",
      largo: 18.6,
      ancho: 2.6,
      alto: 4.3,
      pesoKg: 34500,
      europaleta: 28,
      arlog: 28,
      americano: 28,
    },
    {
      denominacion: "Semiremolque dos ejes 15,5 m",
      clase: "TRAILER",
      division: "SOLIDO",
      largo: 18.6,
      ancho: 2.6,
      alto: 4.3,
      pesoKg: 34500,
      europaleta: 30,
      arlog: 30,
      americano: 30,
    },
    {
      denominacion: "Semiremolque tres ejes 13,5 m",
      clase: "TRAILER",
      division: "SOLIDO",
      largo: 18.6,
      ancho: 2.6,
      alto: 4.3,
      pesoKg: 42000,
      europaleta: 26,
      arlog: 26,
      americano: 26,
    },
    {
      denominacion: "Semiremolque tres ejes 14,5 m",
      clase: "TRAILER",
      division: "SOLIDO",
      largo: 18.6,
      ancho: 2.6,
      alto: 4.3,
      pesoKg: 42000,
      europaleta: 28,
      arlog: 28,
      americano: 28,
    },
    {
      denominacion: "Semiremolque tres ejes 15,5 m",
      clase: "TRAILER",
      division: "SOLIDO",
      largo: 18.6,
      ancho: 2.6,
      alto: 4.3,
      pesoKg: 42000,
      europaleta: 30,
      arlog: 30,
      americano: 30,
    },
    {
      denominacion: "Semiremolque dos ejes con TB 13,5 m",
      clase: "TRAILER",
      division: "SOLIDO",
      largo: 18.6,
      ancho: 2.6,
      alto: 4.3,
      pesoKg: 42000,
      europaleta: 26,
      arlog: 26,
      americano: 26,
    },
    {
      denominacion: "Semiremolque dos ejes con TB 14,5 m",
      clase: "TRAILER",
      division: "SOLIDO",
      largo: 18.6,
      ancho: 2.6,
      alto: 4.3,
      pesoKg: 42000,
      europaleta: 28,
      arlog: 28,
      americano: 28,
    },
    {
      denominacion: "Semiremolque dos ejes con TB 15,5 m",
      clase: "TRAILER",
      division: "SOLIDO",
      largo: 18.6,
      ancho: 2.6,
      alto: 4.3,
      pesoKg: 42000,
      europaleta: 30,
      arlog: 30,
      americano: 30,
    },
    {
      denominacion: "Semi 1 + 1 con TB 13,5 m",
      clase: "TRAILER",
      division: "SOLIDO",
      largo: 18.6,
      ancho: 2.6,
      alto: 4.3,
      pesoKg: 45000,
      europaleta: 26,
      arlog: 26,
      americano: 26,
    },
    {
      denominacion: "Semi 1 + 1 con TB 14,5 m",
      clase: "TRAILER",
      division: "SOLIDO",
      largo: 18.6,
      ancho: 2.6,
      alto: 4.3,
      pesoKg: 45000,
      europaleta: 28,
      arlog: 28,
      americano: 28,
    },
    {
      denominacion: "Semi 1 + 1 con TB 15,5 m",
      clase: "TRAILER",
      division: "SOLIDO",
      largo: 18.6,
      ancho: 2.6,
      alto: 4.3,
      pesoKg: 45000,
      europaleta: 30,
      arlog: 30,
      americano: 30,
    },
    {
      denominacion: "Semiremolque tres ejes con TB 13,5 m",
      clase: "TRAILER",
      division: "SOLIDO",
      largo: 18.6,
      ancho: 2.6,
      alto: 4.3,
      pesoKg: 49500,
      europaleta: 26,
      arlog: 26,
      americano: 26,
    },
    {
      denominacion: "Semiremolque tres ejes con TB 14,5 m",
      clase: "TRAILER",
      division: "SOLIDO",
      largo: 18.6,
      ancho: 2.6,
      alto: 4.3,
      pesoKg: 49500,
      europaleta: 28,
      arlog: 28,
      americano: 28,
    },
    {
      denominacion: "Semiremolque tres ejes con TB 15,5 m",
      clase: "TRAILER",
      division: "SOLIDO",
      largo: 18.6,
      ancho: 2.6,
      alto: 4.3,
      pesoKg: 49500,
      europaleta: 30,
      arlog: 30,
      americano: 30,
    },
    {
      denominacion: "Semiremolque 2 + 1 13,5 m",
      clase: "TRAILER",
      division: "SOLIDO",
      largo: 18.6,
      ancho: 2.6,
      alto: 4.3,
      pesoKg: 45000,
      europaleta: 26,
      arlog: 26,
      americano: 26,
    },
    {
      denominacion: "Semiremolque 2 + 1 14,5 m",
      clase: "TRAILER",
      division: "SOLIDO",
      largo: 18.6,
      ancho: 2.6,
      alto: 4.3,
      pesoKg: 45000,
      europaleta: 28,
      arlog: 28,
      americano: 28,
    },
    {
      denominacion: "Semiremolque 2 + 1 15,5 m",
      clase: "TRAILER",
      division: "SOLIDO",
      largo: 18.6,
      ancho: 2.6,
      alto: 4.3,
      pesoKg: 45000,
      europaleta: 30,
      arlog: 30,
      americano: 30,
    },
    {
      denominacion: "Semiremolque 1 + 1 + 1 14,5 m",
      clase: "TRAILER",
      division: "SOLIDO",
      largo: 18.6,
      ancho: 2.6,
      alto: 4.3,
      pesoKg: 45000,
      europaleta: 28,
      arlog: 28,
      americano: 28,
    },
    {
      denominacion: "Semiremolque 1 + 1 + 1 15,5 m",
      clase: "TRAILER",
      division: "SOLIDO",
      largo: 18.6,
      ancho: 2.6,
      alto: 4.3,
      pesoKg: 45000,
      europaleta: 30,
      arlog: 30,
      americano: 30,
    },
    {
      denominacion: "Chasis acoplado dos ejes 8,6 m",
      clase: "CHASIS",
      division: "SOLIDO",
      largo: 20.0,
      ancho: 2.6,
      alto: 4.3,
      pesoKg: 37500,
      europaleta: 16,
      arlog: 16,
      americano: 16,
    },
    {
      denominacion: "Chasis acoplado dos ejes 9,3 m",
      clase: "CHASIS",
      division: "SOLIDO",
      largo: 20.0,
      ancho: 2.6,
      alto: 4.3,
      pesoKg: 37500,
      europaleta: 18,
      arlog: 18,
      americano: 18,
    },
    {
      denominacion: "Chasis acoplado tres ejes 8,6 m",
      clase: "CHASIS",
      division: "SOLIDO",
      largo: 20.0,
      ancho: 2.6,
      alto: 4.3,
      pesoKg: 45000,
      europaleta: 16,
      arlog: 16,
      americano: 16,
    },
    {
      denominacion: "Chasis acoplado tres ejes 9,3 m",
      clase: "CHASIS",
      division: "SOLIDO",
      largo: 20.0,
      ancho: 2.6,
      alto: 4.3,
      pesoKg: 45000,
      europaleta: 18,
      arlog: 18,
      americano: 18,
    },
    {
      denominacion: "Chasis balancin acoplado dos ejes 8,6 m",
      clase: "CHASIS",
      division: "SOLIDO",
      largo: 20.0,
      ancho: 2.6,
      alto: 4.3,
      pesoKg: 45000,
      europaleta: 16,
      arlog: 16,
      americano: 16,
    },
    {
      denominacion: "Chasis balancin acoplado dos ejes 9,3 m",
      clase: "CHASIS",
      division: "SOLIDO",
      largo: 20.0,
      ancho: 2.6,
      alto: 4.3,
      pesoKg: 45000,
      europaleta: 18,
      arlog: 18,
      americano: 18,
    },
    {
      denominacion: "Chasis balancin acoplado tres ejes 8,6 m",
      clase: "CHASIS",
      division: "SOLIDO",
      largo: 20.0,
      ancho: 2.6,
      alto: 4.3,
      pesoKg: 52500,
      europaleta: 16,
      arlog: 16,
      americano: 16,
    },
    {
      denominacion: "Chasis balancin acoplado tres ejes 9,3 m",
      clase: "CHASIS",
      division: "SOLIDO",
      largo: 20.0,
      ancho: 2.6,
      alto: 4.3,
      pesoKg: 52500,
      europaleta: 18,
      arlog: 18,
      americano: 18,
    },
    {
      denominacion: "Chasis con acoplado cuatro ejes 9,3 m",
      clase: "CHASIS",
      division: "SOLIDO",
      largo: 20.0,
      ancho: 2.6,
      alto: 4.3,
      pesoKg: 52500,
      europaleta: 18,
      arlog: 18,
      americano: 18,
    },
    {
      denominacion: "Chasis con acoplado cuatro ejes 9,6 m",
      clase: "CHASIS",
      division: "SOLIDO",
      largo: 20.0,
      ancho: 2.6,
      alto: 4.3,
      pesoKg: 52500,
      europaleta: 18,
      arlog: 18,
      americano: 18,
    },
    {
      denominacion: "Chasis con acoplado cuatro ejes 10,5 m",
      clase: "CHASIS",
      division: "SOLIDO",
      largo: 20.0,
      ancho: 2.6,
      alto: 4.3,
      pesoKg: 52500,
      europaleta: 20,
      arlog: 20,
      americano: 20,
    },
    {
      denominacion: "Bitren Semiremolque uno y dos ejes",
      clase: "TRAILER",
      division: "SOLIDO",
      largo: 20.5,
      ancho: 2.6,
      alto: 4.3,
      pesoKg: 45000,
      europaleta: null,
      arlog: null,
      americano: null,
    },
    {
      denominacion: "Mosquito dos ejes con TB",
      clase: "TRAILER",
      division: "SOLIDO",
      largo: 22.4,
      ancho: 2.6,
      alto: 4.3,
      pesoKg: 42000,
      europaleta: null,
      arlog: null,
      americano: null,
    },
    {
      denominacion: "Plancha 1 + 1 con TB",
      clase: "TRAILER",
      division: "SOLIDO",
      largo: 22.4,
      ancho: 2.6,
      alto: 4.3,
      pesoKg: 45000,
      europaleta: null,
      arlog: null,
      americano: null,
    },
    {
      denominacion: "Semiremolque 2 + 1 con TB 13,5 m",
      clase: "TRAILER",
      division: "SOLIDO",
      largo: 18.6,
      ancho: 2.6,
      alto: 4.3,
      pesoKg: 52500,
      europaleta: 26,
      arlog: 26,
      americano: 26,
    },
    {
      denominacion: "Semiremolque 2 + 1 con TB 14,5 m",
      clase: "TRAILER",
      division: "SOLIDO",
      largo: 18.6,
      ancho: 2.6,
      alto: 4.3,
      pesoKg: 52500,
      europaleta: 28,
      arlog: 28,
      americano: 28,
    },
    {
      denominacion: "Semiremolque 2 + 1 con TB 15,5 m",
      clase: "TRAILER",
      division: "SOLIDO",
      largo: 18.6,
      ancho: 2.6,
      alto: 4.3,
      pesoKg: 52500,
      europaleta: 30,
      arlog: 30,
      americano: 30,
    },
    {
      denominacion: "Semiremolque 1 + 1 + 1 con TB 13,5 m",
      clase: "TRAILER",
      division: "SOLIDO",
      largo: 18.6,
      ancho: 2.6,
      alto: 4.3,
      pesoKg: 55500,
      europaleta: 26,
      arlog: 26,
      americano: 26,
    },
    {
      denominacion: "Semiremolque 1 + 1 + 1 con TB 14,5 m",
      clase: "TRAILER",
      division: "SOLIDO",
      largo: 18.6,
      ancho: 2.6,
      alto: 4.3,
      pesoKg: 55500,
      europaleta: 28,
      arlog: 28,
      americano: 28,
    },
    {
      denominacion: "Semiremolque 1 + 1 + 1 con TB 15,5 m",
      clase: "TRAILER",
      division: "SOLIDO",
      largo: 18.6,
      ancho: 2.6,
      alto: 4.3,
      pesoKg: 55500,
      europaleta: 30,
      arlog: 30,
      americano: 30,
    },
    {
      denominacion: "Bitren cuatro ejes con TB",
      clase: "TRAILER",
      division: "SOLIDO",
      largo: 20.5,
      ancho: 2.6,
      alto: 4.3,
      pesoKg: 60000,
      europaleta: 34,
      arlog: 34,
      americano: 34,
    },
    {
      denominacion: "Bitren cuatro ejes con TB con permiso circular",
      clase: "TRAILER",
      division: "SOLIDO",
      largo: 22.4,
      ancho: 2.6,
      alto: 4.3,
      pesoKg: 60000,
      europaleta: 38,
      arlog: 38,
      americano: 38,
    },
    {
      denominacion: "Bitren seis ejes con TB",
      clase: "TRAILER",
      division: "SOLIDO",
      largo: 25.5,
      ancho: 2.6,
      alto: 4.3,
      pesoKg: 75000,
      europaleta: 42,
      arlog: 42,
      americano: 42,
    },
    {
      denominacion: "Bitren seis ejes con TB con permiso circular",
      clase: "TRAILER",
      division: "SOLIDO",
      largo: 30.25,
      ancho: 2.6,
      alto: 4.3,
      pesoKg: 75000,
      europaleta: null,
      arlog: null,
      americano: null,
    },
    {
      denominacion: "Cisterna Liquida Chica",
      clase: "TRAILER",
      division: "LIQUIDO",
      largo: 13.0,
      ancho: 2.6,
      alto: 4.3,
      pesoKg: 5000,
      europaleta: null,
      arlog: null,
      americano: null,
    },
    {
      denominacion: "Cisterna Liquida Mediana",
      clase: "TRAILER",
      division: "LIQUIDO",
      largo: 13.0,
      ancho: 2.6,
      alto: 4.3,
      pesoKg: 10000,
      europaleta: null,
      arlog: null,
      americano: null,
    },
    {
      denominacion: "Cisterna Liquida Grande",
      clase: "TRAILER",
      division: "LIQUIDO",
      largo: 13.0,
      ancho: 2.6,
      alto: 4.3,
      pesoKg: 28000,
      europaleta: null,
      arlog: null,
      americano: null,
    },
    {
      denominacion: "Cisterna Liquida Máxima",
      clase: "TRAILER",
      division: "LIQUIDO",
      largo: 13.0,
      ancho: 2.6,
      alto: 4.3,
      pesoKg: 45000,
      europaleta: null,
      arlog: null,
      americano: null,
    },
    {
      denominacion: "Cisterna Granular Chica",
      clase: "TRAILER",
      division: "GRANEL",
      largo: 13.0,
      ancho: 2.6,
      alto: 4.3,
      pesoKg: 5000,
      europaleta: null,
      arlog: null,
      americano: null,
    },
    {
      denominacion: "Cisterna Granular Mediana",
      clase: "TRAILER",
      division: "GRANEL",
      largo: 13.0,
      ancho: 2.6,
      alto: 4.3,
      pesoKg: 10000,
      europaleta: null,
      arlog: null,
      americano: null,
    },
    {
      denominacion: "Cisterna Granular Grande",
      clase: "TRAILER",
      division: "GRANEL",
      largo: 13.0,
      ancho: 2.6,
      alto: 4.3,
      pesoKg: 28000,
      europaleta: null,
      arlog: null,
      americano: null,
    },
    {
      denominacion: "Cisterna Granular Máxima",
      clase: "TRAILER",
      division: "GRANEL",
      largo: 13.0,
      ancho: 2.6,
      alto: 4.3,
      pesoKg: 45000,
      europaleta: null,
      arlog: null,
      americano: null,
    },
    {
      denominacion: "TRACTOR",
      clase: "TRACTOR",
      division: "TODOS",
      largo: 0,
      ancho: 0,
      alto: 0,
      pesoKg: 0,
      europaleta: null,
      arlog: null,
      americano: null,
    },
  ];

  // Opcional en dev: vaciar para poder re-seedear sin conflictos
  await prisma.transporteClasificacion.deleteMany();
  await prisma.transporteClase.deleteMany();
  await prisma.tipoUnidadMedidaVenta.deleteMany();
  await prisma.tipoUnidadMedidaEntrega.deleteMany();
  await prisma.tipoUnidadMedida.deleteMany();
  await prisma.divisionServicio.deleteMany();

  // 1) Crear divisiones de servicio
  const divisionEntities = await prisma.$transaction(
    divisiones.map((division: any) =>
      prisma.divisionServicio.create({
        data: {
          codigo: division.codigo,
          descripcion: division.descripcion,
          habilitado: true,
          created_at: new Date(),
          created_by: "admin",
        },
      })
    )
  );

  // 2) Crear clases de transporte
  const claseEntities = await prisma.$transaction(
    clases.map((clase: any) =>
      prisma.transporteClase.create({
        data: {
          codigo: clase.codigo,
          descripcion: clase.descripcion,
        },
      })
    )
  );

  // 3) Crear unidades de medida (medida, entrega, venta)
  for (const unidad of unidades) {
    const division = divisionEntities.find(
      (div: any) => div.codigo === unidad.division
    );

    if (!division) {
      throw new Error(
        `División no encontrada para el código: ${unidad.division}`
      );
    }

    await prisma.$transaction([
      prisma.tipoUnidadMedida.create({
        data: {
          codigo: unidad.codigo,
          descripcion: unidad.descripcion,
          habilitado: true,
          created_at: new Date(),
          created_by: "admin",
        },
      }),
      prisma.tipoUnidadMedidaEntrega.create({
        data: {
          codigo: unidad.codigo,
          descripcion: unidad.descripcion,
          habilitado: true,
          created_at: new Date(),
          created_by: "admin",
          division_servicio_id: division.id,
        },
      }),
      prisma.tipoUnidadMedidaVenta.create({
        data: {
          codigo: unidad.codigo,
          descripcion: unidad.descripcion,
          habilitado: true,
          created_at: new Date(),
          created_by: "admin",
          division_servicio_id: division.id,
        },
      }),
    ]);
  }

  // 4) Crear clasificaciones de transporte (camiones / remolques / cisternas)
  for (const clasificacionData of clasificaciones) {
    const clase = claseEntities.find(
      (clase: any) => clase.codigo === clasificacionData.clase
    );
    if (!clase) {
      throw new Error(
        `Clase no encontrada para el código: ${clasificacionData.clase}`
      );
    }

    const division = divisionEntities.find(
      (div: any) => div.codigo === clasificacionData.division
    );
    if (!division) {
      throw new Error(
        `División no encontrada para el código: ${clasificacionData.division}`
      );
    }

    await prisma.transporteClasificacion.create({
      data: {
        denominacion_de_vehiculo: clasificacionData.denominacion,
        mt_largo_cub: Math.round(clasificacionData.largo ?? 0),
        mt_ancho_cub: Math.round(clasificacionData.ancho ?? 0),
        mt_alto_cub: Math.round(clasificacionData.alto ?? 0),
        mt_total_cub: 0,
        max_peso_kg: clasificacionData.pesoKg ?? 0,
        max_peso_lt:
          division.codigo === "LIQUIDO" ? clasificacionData.pesoKg ?? 0 : 0,
        max_peso_xmt3: 0,
        pallet_europaleta_total: clasificacionData.europaleta ?? 0,
        pallet_ariog_total: clasificacionData.arlog?.toString() ?? "",
        pallet_americano_total: clasificacionData.americano?.toString() ?? "",
        clase_transporte_id: clase.id,
        division_servicio_id: division.id,
      },
    });
  }

  console.log("✅ Seed de división, unidades y transporte ejecutado");
}
